package io.github.rafaelrabeloit.emv

import io.github.rafaelrabeloit.bertlv.Specification
import io.github.rafaelrabeloit.bertlv.components.TLVTag
import io.github.rafaelrabeloit.emv.value.AlphanumericValueParser
import io.github.rafaelrabeloit.emv.value.BinaryValueParser
import io.github.rafaelrabeloit.emv.value.NumericNumberValueParser
import io.github.rafaelrabeloit.emv.value.NumericValueParser
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class EmvSpecificationTest {
    private val specification = EmvSpecification

    @Test
    fun `Given existing tag When check if exists Then should return true`() {
        val tag = TLVTag.fromTag(0x9F26)
        val exists = specification.tagExists(tag)
        assertEquals(true, exists)
    }

    @Test
    fun `Given non existing tag When check if exists Then should return false`() {
        val tag = TLVTag.fromTag(0x9F99)
        val exists = specification.tagExists(tag)
        assertEquals(false, exists)
    }

    @Test
    fun `Given existing tag When get context Then should return correct context`() {
        val tag = TLVTag.fromTag(0x9F26)
        val context = specification.contextForTag(tag)
        assertEquals("Application Cryptogram", context.info)
        assertEquals("Cryptogram generated by the card for transaction authentication", context.description)
    }

    @Test
    fun `Given non existing tag When get context Then should throw exception`() {
        val tag = TLVTag.fromTag(0x9F99)
        assertFailsWith<Specification.TagNotExistException> {
            specification.contextForTag(tag)
        }
    }

    @Test
    fun `Given numeric tag When get value handler Then should return numeric value handler`() {
        val tag = TLVTag.fromTag(0x5A)
        val handler = specification.handlerOfValue(tag)
        assertNotNull(handler)
        assertTrue(handler.parser is NumericValueParser)
    }

    @Test
    fun `Given binary tag When get value handler Then should return binary value handler`() {
        val tag = TLVTag.fromTag(0x9F26)
        val handler = specification.handlerOfValue(tag)
        assertNotNull(handler)
        assertTrue(handler.parser is BinaryValueParser)
    }

    @Test
    fun `Given alphanumeric tag When get value handler Then should return alphanumeric value handler`() {
        val tag = TLVTag.fromTag(0x9F20)
        val handler = specification.handlerOfValue(tag)
        assertNotNull(handler)
        assertTrue(handler.parser is AlphanumericValueParser)
    }

    @Test
    fun `Given alphanumeric special tag When get value handler Then should return alphanumeric special handler`() {
        val tag = TLVTag.fromTag(0x9F4E)
        val handler = specification.handlerOfValue(tag)
        assertNotNull(handler)
        assertTrue(handler.parser is AlphanumericValueParser)
    }

    @Test
    fun `Given non existing tag When get value handler Then should throw exception`() {
        val tag = TLVTag.fromTag(0x9F99)
        assertFailsWith<Specification.TagNotExistException> {
            specification.handlerOfValue(tag)
        }
    }

    @Test
    fun `handlerOfValue returns NumericNumberValueParser for amount tags`() {
        // Test AMOUNT_AUTHORISED tag
        val amountAuthorisedTag = TLVTag.fromTag(0x9F02)
        val amountAuthorisedHandler = EmvSpecification.handlerOfValue(amountAuthorisedTag)
        assertTrue(amountAuthorisedHandler.parser is NumericNumberValueParser)
    }
}
