package io.github.rafaelrabeloit.iso

/**
 *  ISO 18245:2003
 */
enum class MerchantCategoryCodeDescription(
    val code: Int,
    val description: String,
    val category: String,
) {
    MCC0742(742, "Veterinary services", "Agricultural services"),
    MCC0743(743, "Wine producers", "Agricultural services"),
    MCC0744(744, "Champagne producers", "Agricultural services"),
    MCC0763(763, "Agricultural co-operatives", "Agricultural services"),
    MCC0780(780, "Landscaping and horticultural services", "Agricultural services"),
    MCC1520(1520, "General contractors — residential and commercial", "Contracted services"),
    MCC1711(1711, "Heating, plumbing and air-conditioning contractors", "Contracted services"),
    MCC1731(1731, "Electrical contractors", "Contracted services"),
    MCC1740(1740, "Masonry, stonework, tile setting, plastering and insulation contractors", "Contracted services"),
    MCC1750(1750, "Carpentry contractors", "Contracted services"),
    MCC1761(1761, "Roofing, siding and sheet metal work contractors", "Contracted services"),
    MCC1771(1771, "Concrete work contractors", "Contracted services"),
    MCC1799(1799, "Special trade contractors — not elsewhere classified", "Contracted services"),
    MCC2741(2741, "Miscellaneous publishing and printing services", "Contracted services"),
    MCC2791(2791, "Typesetting, platemaking and related services", "Contracted services"),
    MCC2842(2842, "Speciality cleaning, polishing and sanitation preparations", "Contracted services"),
    MCC4011(4011, "Railroads", "Transportation"),
    MCC4111(4111, "Local and suburban commuter passenger transportation, including ferries", "Transportation"),
    MCC4112(4112, "Passenger railways", "Transportation"),
    MCC4119(4119, "Ambulance services", "Transportation"),
    MCC4121(4121, "Taxi-cabs and limousines", "Transportation"),
    MCC4131(4131, "Bus lines", "Transportation"),
    MCC4214(
        4214,
        "Motor freight carriers and trucking — " +
            "local and long distance, moving and storage companies and local delivery",
        "Transportation",
    ),
    MCC4215(4215, "Courier services — air and ground and freight forwarders", "Transportation"),
    MCC4225(
        4225,
        "Public warehousing and storage — farm products, refrigerated goods and household goods",
        "Transportation",
    ),
    MCC4411(4411, "Steamships and cruise lines", "Transportation"),
    MCC4457(4457, "Boat rentals and leasing", "Transportation"),
    MCC4468(4468, "Marinas, marine service and supplies", "Transportation"),
    MCC4511(4511, "Airlines and air carriers", "Transportation"),
    MCC4582(4582, "Airports, flying fields and airport terminals", "Transportation"),
    MCC4722(4722, "Travel agencies and tour operators", "Transportation"),
    MCC4784(4784, "Tolls and bridge fees", "Transportation"),
    MCC4789(4789, "Transportation services — not elsewhere classified", "Transportation"),
    MCC4812(4812, "Telecommunication equipment and telephone sales", "Utilities"),
    MCC4814(
        4814,
        "Telecommunication services, including local and long distance calls, credit card calls, " +
            "calls through use of magnetic stripe reading telephones and faxes",
        "Utilities",
    ),
    MCC4815(4815, "Monthly summary telephone charges", "Utilities"),
    MCC4816(4816, "Computer network/information services", "Utilities"),
    MCC4821(4821, "Telegraph services", "Utilities"),
    MCC4829(4829, "Wire transfers and money orders", "Utilities"),
    MCC4899(4899, "Cable and other pay television services", "Utilities"),
    MCC4900(4900, "Utilities — electric, gas, water and sanitary", "Utilities"),
    MCC5013(5013, "Motor vehicle supplies and new parts", "Retail outlets"),
    MCC5021(5021, "Office and commercial furniture", "Retail outlets"),
    MCC5039(5039, "Construction materials — not elsewhere classified", "Retail outlets"),
    MCC5044(5044, "Office, photographic, photocopy and microfilm equipment", "Retail outlets"),
    MCC5045(5045, "Computers, computer peripheral equipment — not elsewhere classified", "Retail outlets"),
    MCC5046(5046, "Commercial equipment — not elsewhere classified", "Retail outlets"),
    MCC5047(5047, "Dental/laboratory/medical/ophthalmic hospital equipment and supplies", "Retail outlets"),
    MCC5051(5051, "Metal service centres and offices", "Retail outlets"),
    MCC5065(5065, "Electrical parts and equipment", "Retail outlets"),
    MCC5072(5072, "Hardware equipment and supplies", "Retail outlets"),
    MCC5074(5074, "Plumbing and heating equipment and supplies", "Retail outlets"),
    MCC5085(5085, "Industrial supplies — not elsewhere classified", "Retail outlets"),
    MCC5094(5094, "Precious stones and metals, watches and jewellery", "Retail outlets"),
    MCC5099(5099, "Durable goods — not elsewhere classified", "Retail outlets"),
    MCC5111(5111, "Stationery, office supplies and printing and writing paper", "Retail outlets"),
    MCC5122(5122, "Drugs, drug proprietors", "Retail outlets"),
    MCC5131(5131, "Piece goods, notions and other dry goods", "Retail outlets"),
    MCC5137(5137, "Men’s, women’s and children’s uniforms and commercial clothing", "Retail outlets"),
    MCC5139(5139, "Commercial footwear", "Retail outlets"),
    MCC5169(5169, "Chemicals and allied products — not elsewhere classified", "Retail outlets"),
    MCC5172(5172, "Petroleum and petroleum products", "Retail outlets"),
    MCC5192(5192, "Books, periodicals and newspapers", "Retail outlets"),
    MCC5193(5193, "Florists’ supplies, nursery stock and flowers", "Retail outlets"),
    MCC5198(5198, "Paints, varnishes and supplies", "Retail outlets"),
    MCC5199(5199, "Non-durable goods — not elsewhere classified", "Retail outlets"),
    MCC5200(5200, "Home supply warehouse outlets", "Retail outlets"),
    MCC5211(5211, "Lumber and building materials outlets", "Retail outlets"),
    MCC5231(5231, "Glass, paint and wallpaper shops", "Retail outlets"),
    MCC5251(5251, "Hardware shops", "Retail outlets"),
    MCC5261(5261, "Lawn and garden supplies outlets, including nurseries", "Retail outlets"),
    MCC5271(5271, "Mobile home dealers", "Retail outlets"),
    MCC5300(5300, "Wholesale clubs", "Retail outlets"),
    MCC5309(5309, "Duty-free shops", "Retail outlets"),
    MCC5310(5310, "Discount shops", "Retail outlets"),
    MCC5311(5311, "Department stores", "Retail outlets"),
    MCC5331(5331, "Variety stores", "Retail outlets"),
    MCC5399(5399, "Miscellaneous general merchandise", "Retail outlets"),
    MCC5411(5411, "Groceries and supermarkets", "Retail outlets"),
    MCC5422(5422, "Freezer and locker meat provisioners", "Retail outlets"),
    MCC5441(5441, "Candy, nut and confectionery shops", "Retail outlets"),
    MCC5451(5451, "Dairies", "Retail outlets"),
    MCC5462(5462, "Bakeries", "Retail outlets"),
    MCC5499(5499, "Miscellaneous food shops — convenience and speciality retail outlets", "Retail outlets"),
    MCC5511(
        5511,
        "Car and truck dealers (new and used) sales, services, repairs, parts and leasing",
        "Automobiles and vehicles",
    ),
    MCC5521(
        5521,
        "Car and truck dealers (used only) sales, service, repairs, parts and leasing",
        "Automobiles and vehicles",
    ),
    MCC5531(5531, "Auto and home supply outlets", "Automobiles and vehicles"),
    MCC5532(5532, "Automotive tyre outlets", "Automobiles and vehicles"),
    MCC5533(5533, "Automotive parts and accessories outlets", "Automobiles and vehicles"),
    MCC5541(5541, "Service stations (with or without ancillary services)", "Automobiles and vehicles"),
    MCC5542(5542, "Automated fuel dispensers", "Automobiles and vehicles"),
    MCC5551(5551, "Boat dealers", "Automobiles and vehicles"),
    MCC5561(5561, "Camper, recreational and utility trailer dealers", "Automobiles and vehicles"),
    MCC5571(5571, "Motorcycle shops and dealers", "Automobiles and vehicles"),
    MCC5592(5592, "Motor home dealers", "Automobiles and vehicles"),
    MCC5598(5598, "Snowmobile dealers", "Automobiles and vehicles"),
    MCC5599(
        5599,
        "Miscellaneous automotive, aircraft and farm equipment dealers — not elsewhere classified",
        "Automobiles and vehicles",
    ),
    MCC5611(5611, "Men’s and boys’ clothing and accessory shops", "Clothing outlets"),
    MCC5621(5621, "Women’s ready-to-wear shops", "Clothing outlets"),
    MCC5631(5631, "Women’s accessory and speciality shops", "Clothing outlets"),
    MCC5641(5641, "Children’s and infants’ wear shops", "Clothing outlets"),
    MCC5651(5651, "Family clothing shops", "Clothing outlets"),
    MCC5655(5655, "Sports and riding apparel shops", "Clothing outlets"),
    MCC5661(5661, "Shoe shops", "Clothing outlets"),
    MCC5681(5681, "Furriers and fur shops", "Clothing outlets"),
    MCC5691(5691, "Men’s and women’s clothing shops", "Clothing outlets"),
    MCC5697(5697, "Tailors, seamstresses, mending and alterations", "Clothing outlets"),
    MCC5698(5698, "Wig and toupee shops", "Clothing outlets"),
    MCC5699(5699, "Miscellaneous apparel and accessory shops", "Clothing outlets"),
    MCC5712(
        5712,
        "Furniture, home furnishings and equipment shops and manufacturers, except appliances",
        "Miscellaneous outlets",
    ),
    MCC5713(5713, "Floor covering services", "Miscellaneous outlets"),
    MCC5714(5714, "Drapery, window covering and upholstery shops", "Miscellaneous outlets"),
    MCC5715(5715, "Alcoholic beverage wholesalers", "Miscellaneous outlets"),
    MCC5718(5718, "Fireplaces, fireplace screens and accessories shops", "Miscellaneous outlets"),
    MCC5719(5719, "Miscellaneous home furnishing speciality shops", "Miscellaneous outlets"),
    MCC5722(5722, "Household appliance shops", "Miscellaneous outlets"),
    MCC5732(5732, "Electronics shops", "Miscellaneous outlets"),
    MCC5733(5733, "Music shops — musical instruments, pianos and sheet music", "Miscellaneous outlets"),
    MCC5734(5734, "Computer software outlets", "Miscellaneous outlets"),
    MCC5735(5735, "Record shops", "Miscellaneous outlets"),
    MCC5811(5811, "Caterers", "Miscellaneous outlets"),
    MCC5812(5812, "Eating places and restaurants", "Miscellaneous outlets"),
    MCC5813(
        5813,
        "Drinking places (alcoholic beverages) — bars, taverns, night-clubs, cocktail lounges and discothèques",
        "Miscellaneous outlets",
    ),
    MCC5814(5814, "Fast food restaurants", "Miscellaneous outlets"),
    MCC5815(5815, "Digital Goods-Media: Books, Movies, Music", "Miscellaneous outlets"),
    MCC5816(5816, "Digital Goods: Games", "Miscellaneous outlets"),
    MCC5817(5817, "Digital Goods: Application (Excludes Games)", "Miscellaneous outlets"),
    MCC5818(5818, "Large Digital Goods Merchant", "Miscellaneous outlets"),
    MCC5912(5912, "Drug stores and pharmacies", "Miscellaneous outlets"),
    MCC5921(5921, "Package shops — beer, wine and liquor", "Miscellaneous outlets"),
    MCC5931(5931, "Used merchandise and second-hand shops", "Miscellaneous outlets"),
    MCC5932(5932, "Antique shops — sales, repairs and restoration services", "Miscellaneous outlets"),
    MCC5933(5933, "Pawn shops", "Miscellaneous outlets"),
    MCC5935(5935, "Wrecking and salvage yards", "Miscellaneous outlets"),
    MCC5937(5937, "Antique reproduction shops", "Miscellaneous outlets"),
    MCC5940(5940, "Bicycle shops — sales and service", "Miscellaneous outlets"),
    MCC5941(5941, "Sporting goods shops", "Miscellaneous outlets"),
    MCC5942(5942, "Bookshops", "Miscellaneous outlets"),
    MCC5943(5943, "Stationery, office and school supply shops", "Miscellaneous outlets"),
    MCC5944(5944, "Jewellery, watch, clock and silverware shops", "Miscellaneous outlets"),
    MCC5945(5945, "Hobby, toy and game shops", "Miscellaneous outlets"),
    MCC5946(5946, "Camera and photographic supply shops", "Miscellaneous outlets"),
    MCC5947(5947, "Gift, card, novelty and souvenir shops", "Miscellaneous outlets"),
    MCC5948(5948, "Luggage and leather goods shops", "Miscellaneous outlets"),
    MCC5949(5949, "Sewing, needlework, fabric and piece goods shops", "Miscellaneous outlets"),
    MCC5950(5950, "Glassware and crystal shops", "Miscellaneous outlets"),
    MCC5960(5960, "Direct marketing — insurance services", "Miscellaneous outlets"),
    MCC5962(5962, "Telemarketing — travel-related arrangement services", "Miscellaneous outlets"),
    MCC5963(5963, "Door-to-door sales", "Miscellaneous outlets"),
    MCC5964(5964, "Direct marketing — catalogue merchants", "Miscellaneous outlets"),
    MCC5965(5965, "Direct marketing — combination catalogue and retail merchants", "Miscellaneous outlets"),
    MCC5966(5966, "Direct marketing — outbound telemarketing merchants", "Miscellaneous outlets"),
    MCC5967(5967, "Direct marketing — inbound telemarketing merchants", "Miscellaneous outlets"),
    MCC5968(5968, "Direct marketing — continuity/subscription merchants", "Miscellaneous outlets"),
    MCC5969(5969, "Direct marketing/direct marketers — not elsewhere classified", "Miscellaneous outlets"),
    MCC5970(5970, "Artist supply and craft shops", "Miscellaneous outlets"),
    MCC5971(5971, "Art dealers and galleries", "Miscellaneous outlets"),
    MCC5972(5972, "Stamp and coin shops", "Miscellaneous outlets"),
    MCC5973(5973, "Religious goods and shops", "Miscellaneous outlets"),
    MCC5975(5975, "Hearing aids — sales, service and supplies", "Miscellaneous outlets"),
    MCC5976(5976, "Orthopaedic goods and prosthetic devices", "Miscellaneous outlets"),
    MCC5977(5977, "Cosmetic shops", "Miscellaneous outlets"),
    MCC5978(5978, "Typewriter outlets — sales, service and rentals", "Miscellaneous outlets"),
    MCC5983(5983, "Fuel dealers — fuel oil, wood, coal and liquefied petroleum", "Miscellaneous outlets"),
    MCC5992(5992, "Florists", "Miscellaneous outlets"),
    MCC5993(5993, "Cigar shops and stands", "Miscellaneous outlets"),
    MCC5994(5994, "Newsagents and news-stands", "Miscellaneous outlets"),
    MCC5995(5995, "Pet shops, pet food and supplies", "Miscellaneous outlets"),
    MCC5996(5996, "Swimming pools — sales, supplies and services", "Miscellaneous outlets"),
    MCC5997(5997, "Electric razor shops — sales and service", "Miscellaneous outlets"),
    MCC5998(5998, "Tent and awning shops", "Miscellaneous outlets"),
    MCC5999(5999, "Miscellaneous and speciality retail outlets", "Miscellaneous outlets"),
    MCC6010(6010, "Financial institutions — manual cash disbursements", "Service providers"),
    MCC6011(6011, "Financial institutions — automated cash disbursements", "Service providers"),
    MCC6012(6012, "Financial institutions — merchandise and services", "Service providers"),
    MCC6051(
        6051,
        "Non-financial institutions — foreign currency, money orders (not wire transfer), scrip and travellers’ checks",
        "Service providers",
    ),
    MCC6211(6211, "Securities — brokers and dealers", "Service providers"),
    MCC6300(6300, "Insurance sales, underwriting and premiums", "Service providers"),
    MCC7011(7011, "Lodging — hotels, motels and resorts", "Service providers"),
    MCC7012(7012, "Timeshares", "Service providers"),
    MCC7032(7032, "Sporting and recreational camps", "Service providers"),
    MCC7033(7033, "Trailer parks and camp-sites", "Service providers"),
    MCC7210(7210, "Laundry, cleaning and garment services", "Service providers"),
    MCC7211(7211, "Laundry services — family and commercial", "Service providers"),
    MCC7216(7216, "Dry cleaners", "Service providers"),
    MCC7217(7217, "Carpet and upholstery cleaning", "Service providers"),
    MCC7221(7221, "Photographic studios", "Service providers"),
    MCC7230(7230, "Beauty and barber shops", "Service providers"),
    MCC7251(7251, "Shoe repair shops, shoe shine parlours and hat cleaning shops", "Service providers"),
    MCC7261(7261, "Funeral services and crematoriums", "Service providers"),
    MCC7273(7273, "Dating and escort services", "Service providers"),
    MCC7276(7276, "Tax preparation services", "Service providers"),
    MCC7277(7277, "Counselling services — debt, marriage and personal", "Service providers"),
    MCC7278(7278, "Buying and shopping services and clubs", "Service providers"),
    MCC7296(7296, "Clothing rentals — costumes, uniforms and formal wear", "Service providers"),
    MCC7297(7297, "Massage parlours", "Service providers"),
    MCC7298(7298, "Health and beauty spas", "Service providers"),
    MCC7299(7299, "Miscellaneous personal services — not elsewhere classified", "Service providers"),
    MCC7311(7311, "Advertising services", "Business services"),
    MCC7321(7321, "Consumer credit reporting agencies", "Business services"),
    MCC7322(7322, "Debt collection agencies", "Business services"),
    MCC7333(7333, "Commercial photography, art and graphics", "Business services"),
    MCC7338(7338, "Quick copy, reproduction and blueprinting services", "Business services"),
    MCC7339(7339, "Stenographic and secretarial support services", "Business services"),
    MCC7342(7342, "Exterminating and disinfecting services", "Business services"),
    MCC7349(7349, "Cleaning, maintenance and janitorial services", "Business services"),
    MCC7361(7361, "Employment agencies and temporary help services", "Business services"),
    MCC7372(7372, "Computer programming, data processing and integrated systems design services", "Business services"),
    MCC7375(7375, "Information retrieval services", "Business services"),
    MCC7379(7379, "Computer maintenance and repair services — not elsewhere classified", "Business services"),
    MCC7392(7392, "Management, consulting and public relations services", "Business services"),
    MCC7393(
        7393,
        "Detective agencies, protective agencies and security services, including armoured cars and guard dogs",
        "Business services",
    ),
    MCC7394(7394, "Equipment, tool, furniture and appliance rentals and leasing", "Business services"),
    MCC7395(7395, "Photofinishing laboratories and photo developing", "Business services"),
    MCC7399(7399, "Business services — not elsewhere classified", "Business services"),
    MCC7512(7512, "Automobile rentals", "Business services"),
    MCC7513(7513, "Truck and utility trailer rentals", "Business services"),
    MCC7519(7519, "Motor home and recreational vehicle rentals", "Business services"),
    MCC7523(7523, "Parking lots and garages", "Business services"),
    MCC7531(7531, "Automotive body repair shops", "Repair services"),
    MCC7534(7534, "Tyre retreading and repair shops", "Repair services"),
    MCC7535(7535, "Automotive paint shops", "Repair services"),
    MCC7538(7538, "Automotive service shops (non-dealer)", "Repair services"),
    MCC7542(7542, "Car washes", "Repair services"),
    MCC7549(7549, "Towing services", "Repair services"),
    MCC7622(7622, "Electronics repair shops", "Repair services"),
    MCC7623(7623, "Air conditioning and refrigeration repair shops", "Repair services"),
    MCC7629(7629, "Electrical and small appliance repair shops", "Repair services"),
    MCC7631(7631, "Watch, clock and jewellery repair shops", "Repair services"),
    MCC7641(7641, "Furniture reupholstery, repair and refinishing", "Repair services"),
    MCC7692(7692, "Welding services", "Repair services"),
    MCC7699(7699, "Miscellaneous repair shops and related services", "Repair services"),
    MCC7800(7800, "Government Owned Lotteries", "Amusement and entertainment"),
    MCC7801(7801, "Government Licensed Online Casinos (On-Line Gambling)", "Amusement and entertainment"),
    MCC7802(7802, "Government-licensed Horse/Dog Racing", "Amusement and entertainment"),
    MCC7829(7829, "Motion picture and video tape production and distribution", "Amusement and entertainment"),
    MCC7832(7832, "Motion picture theatres", "Amusement and entertainment"),
    MCC7841(7841, "Video tape rentals", "Amusement and entertainment"),
    MCC7911(7911, "Dance halls, studios and schools", "Amusement and entertainment"),
    MCC7922(7922, "Theatrical producers (except motion pictures) and ticket agencies", "Amusement and entertainment"),
    MCC7929(
        7929,
        "Bands, orchestras and miscellaneous entertainers — not elsewhere classified",
        "Amusement and entertainment",
    ),
    MCC7932(7932, "Billiard and pool establishments", "Amusement and entertainment"),
    MCC7933(7933, "Bowling alleys", "Amusement and entertainment"),
    MCC7941(
        7941,
        "Commercial sports, professional sports clubs, athletic fields and sports promoters",
        "Amusement and entertainment",
    ),
    MCC7991(7991, "Tourist attractions and exhibits", "Amusement and entertainment"),
    MCC7992(7992, "Public golf courses", "Amusement and entertainment"),
    MCC7993(7993, "Video amusement game supplies", "Amusement and entertainment"),
    MCC7994(7994, "Video game arcades and establishments", "Amusement and entertainment"),
    MCC7995(
        7995,
        "Betting, including lottery tickets, casino gaming chips, off-track betting and wagers at race tracks.",
        "Amusement and entertainment",
    ),
    MCC7996(7996, "Amusement parks, circuses, carnivals and fortune tellers", "Amusement and entertainment"),
    MCC7997(
        7997,
        "Membership clubs (sports, recreation, athletic), country clubs and private golf courses",
        "Amusement and entertainment",
    ),
    MCC7998(7998, "Aquariums, seaquariums and dolphinariums", "Amusement and entertainment"),
    MCC7999(7999, "Recreation services — not elsewhere classified", "Amusement and entertainment"),
    MCC8011(
        8011,
        "Doctors and physicians — not elsewhere classified",
        "Professional services and membership organizations",
    ),
    MCC8021(8021, "Dentists and orthodontists", "Professional services and membership organizations"),
    MCC8031(8031, "Osteopaths", "Professional services and membership organizations"),
    MCC8041(8041, "Chiropractors", "Professional services and membership organizations"),
    MCC8042(8042, "Optometrists and ophthalmologists", "Professional services and membership organizations"),
    MCC8043(8043, "Opticians, optical goods and eyeglasses", "Professional services and membership organizations"),
    MCC8049(8049, "Podiatrists and chiropodists", "Professional services and membership organizations"),
    MCC8050(8050, "Nursing and personal care facilities", "Professional services and membership organizations"),
    MCC8062(8062, "Hospitals", "Professional services and membership organizations"),
    MCC8071(8071, "Medical and dental laboratories", "Professional services and membership organizations"),
    MCC8099(
        8099,
        "Medical services and health practitioners — not elsewhere classified",
        "Professional services and membership organizations",
    ),
    MCC8111(8111, "Legal services and attorneys", "Professional services and membership organizations"),
    MCC8211(8211, "Elementary and secondary schools", "Professional services and membership organizations"),
    MCC8220(
        8220,
        "Colleges, universities, professional schools and junior colleges",
        "Professional services and membership organizations",
    ),
    MCC8241(8241, "Correspondence schools", "Professional services and membership organizations"),
    MCC8244(8244, "Business and secretarial schools", "Professional services and membership organizations"),
    MCC8249(8249, "Trade and vocational schools", "Professional services and membership organizations"),
    MCC8299(
        8299,
        "Schools and educational services — not elsewhere classified",
        "Professional services and membership organizations",
    ),
    MCC8351(8351, "Child care services", "Professional services and membership organizations"),
    MCC8398(8398, "Charitable and social service organizations", "Professional services and membership organizations"),
    MCC8641(8641, "Civic, social and fraternal associations", "Professional services and membership organizations"),
    MCC8651(8651, "Political organizations", "Professional services and membership organizations"),
    MCC8661(8661, "Religious organizations", "Professional services and membership organizations"),
    MCC8675(8675, "Automobile associations", "Professional services and membership organizations"),
    MCC8699(
        8699,
        "Membership organizations — not elsewhere classified",
        "Professional services and membership organizations",
    ),
    MCC8734(8734, "Testing laboratories (non-medical)", "Professional services and membership organizations"),
    MCC8911(
        8911,
        "Architectural, engineering and surveying services",
        "Professional services and membership organizations",
    ),
    MCC8931(
        8931,
        "Accounting, auditing and bookkeeping services",
        "Professional services and membership organizations",
    ),
    MCC8999(
        8999,
        "Professional services — not elsewhere classified",
        "Professional services and membership organizations",
    ),
    MCC9211(9211, "Court costs, including alimony and child support", "Government services"),
    MCC9222(9222, "Fines", "Government services"),
    MCC9223(9223, "Bail and bond payments", "Government services"),
    MCC9311(9311, "Tax payments", "Government services"),
    MCC9399(9399, "Government services — not elsewhere classified", "Government services"),
    MCC9402(9402, "Postal services — government only", "Government services"),
    ;

    companion object {
        fun fromCode(code: Int): MerchantCategoryCodeDescription? =
            entries.find { it.code == code }
    }
}
