package io.github.rafaelrabeloit.iso

/**
 * ISO 3166
 */
enum class CountryCodeDescription(
    val numericCode: Int,
    val description: String,
    val alpha2Code: String,
    val alpha3Code: String,
) {
    AX(248, "Aaland Islands", "AX", "ALA"),
    AF(4, "Afghanistan", "AF", "AFG"),
    AL(8, "Albania", "AL", "ALB"),
    DZ(12, "Algeria", "DZ", "DZA"),
    AS(16, "American Samoa", "AS", "ASM"),
    AD(20, "Andorra", "AD", "AND"),
    AO(24, "Angola", "AO", "AGO"),
    AI(660, "Anguilla", "AI", "AIA"),
    AQ(10, "Antarctica", "AQ", "ATA"),
    AG(28, "Antigua And Barbuda", "AG", "ATG"),
    AR(32, "Argentina", "AR", "ARG"),
    AM(51, "Armenia", "AM", "ARM"),
    AW(533, "Aruba", "AW", "ABW"),
    AU(36, "Australia", "AU", "AUS"),
    AT(40, "Austria", "AT", "AUT"),
    AZ(31, "Azerbaijan", "AZ", "AZE"),
    BS(44, "Bahamas", "BS", "BHS"),
    BH(48, "Bahrain", "BH", "BHR"),
    BD(50, "Bangladesh", "BD", "BGD"),
    BB(52, "Barbados", "BB", "BRB"),
    BY(112, "Belarus", "BY", "BLR"),
    BE(56, "Belgium", "BE", "BEL"),
    BZ(84, "Belize", "BZ", "BLZ"),
    BJ(204, "Benin", "BJ", "BEN"),
    BM(60, "Bermuda", "BM", "BMU"),
    BT(64, "Bhutan", "BT", "BTN"),
    BO(68, "Bolivia", "BO", "BOL"),
    BA(70, "Bosnia And Herzegowina", "BA", "BIH"),
    BW(72, "Botswana", "BW", "BWA"),
    BV(74, "Bouvet Island", "BV", "BVT"),
    BR(76, "Brazil", "BR", "BRA"),
    IO(86, "British Indian Ocean Territory", "IO", "IOT"),
    BN(96, "Brunei Darussalam", "BN", "BRN"),
    BG(100, "Bulgaria", "BG", "BGR"),
    BF(854, "Burkina Faso", "BF", "BFA"),
    BI(108, "Burundi", "BI", "BDI"),
    KH(116, "Cambodia", "KH", "KHM"),
    CM(120, "Cameroon", "CM", "CMR"),
    CA(124, "Canada", "CA", "CAN"),
    CV(132, "Cape Verde", "CV", "CPV"),
    KY(136, "Cayman Islands", "KY", "CYM"),
    CF(140, "Central African Republic", "CF", "CAF"),
    TD(148, "Chad", "TD", "TCD"),
    CL(152, "Chile", "CL", "CHL"),
    CN(156, "China", "CN", "CHN"),
    CX(162, "Christmas Island", "CX", "CXR"),
    CC(166, "Cocos (Keeling) Islands", "CC", "CCK"),
    CO(170, "Colombia", "CO", "COL"),
    KM(174, "Comoros", "KM", "COM"),
    CK(184, "Cook Islands", "CK", "COK"),
    CR(188, "Costa Rica", "CR", "CRI"),
    CI(384, "Cote D'Ivoire", "CI", "CIV"),
    CU(192, "Cuba", "CU", "CUB"),
    CY(196, "Cyprus", "CY", "CYP"),
    CZ(203, "Czech Republic", "CZ", "CZE"),
    DK(208, "Denmark", "DK", "DNK"),
    DJ(262, "Djibouti", "DJ", "DJI"),
    DM(212, "Dominica", "DM", "DMA"),
    DO(214, "Dominican Republic", "DO", "DOM"),
    EC(218, "Ecuador", "EC", "ECU"),
    EG(818, "Egypt", "EG", "EGY"),
    SV(222, "El Salvador", "SV", "SLV"),
    GQ(226, "Equatorial Guinea", "GQ", "GNQ"),
    ER(232, "Eritrea", "ER", "ERI"),
    EE(233, "Estonia", "EE", "EST"),
    ET(231, "Ethiopia", "ET", "ETH"),
    FK(238, "Falkland Islands (Malvinas)", "FK", "FLK"),
    FO(234, "Faroe Islands", "FO", "FRO"),
    FJ(242, "Fiji", "FJ", "FJI"),
    FI(246, "Finland", "FI", "FIN"),
    FR(250, "France", "FR", "FRA"),
    GF(254, "French Guiana", "GF", "GUF"),
    PF(258, "French Polynesia", "PF", "PYF"),
    TF(260, "French Southern Territories", "TF", "ATF"),
    GA(266, "Gabon", "GA", "GAB"),
    GM(270, "Gambia", "GM", "GMB"),
    GE(268, "Georgia", "GE", "GEO"),
    DE(276, "Germany", "DE", "DEU"),
    GH(288, "Ghana", "GH", "GHA"),
    GI(292, "Gibraltar", "GI", "GIB"),
    GR(300, "Greece", "GR", "GRC"),
    GL(304, "Greenland", "GL", "GRL"),
    GD(308, "Grenada", "GD", "GRD"),
    GP(312, "Guadeloupe", "GP", "GLP"),
    GU(316, "Guam", "GU", "GUM"),
    GT(320, "Guatemala", "GT", "GTM"),
    GN(324, "Guinea", "GN", "GIN"),
    GW(624, "Guinea-Bissau", "GW", "GNB"),
    GY(328, "Guyana", "GY", "GUY"),
    HT(332, "Haiti", "HT", "HTI"),
    HM(334, "Heard And Mc Donald Islands", "HM", "HMD"),
    HN(340, "Honduras", "HN", "HND"),
    HK(344, "Hong Kong", "HK", "HKG"),
    HU(348, "Hungary", "HU", "HUN"),
    IS(352, "Iceland", "IS", "ISL"),
    IN(356, "India", "IN", "IND"),
    ID(360, "Indonesia", "ID", "IDN"),
    IR(364, "Iran (Islamic Republic Of)", "IR", "IRN"),
    IQ(368, "Iraq", "IQ", "IRQ"),
    IE(372, "Ireland", "IE", "IRL"),
    IT(380, "Italy", "IT", "ITA"),
    JM(388, "Jamaica", "JM", "JAM"),
    JP(392, "Japan", "JP", "JPN"),
    JO(400, "Jordan", "JO", "JOR"),
    KZ(398, "Kazakhstan", "KZ", "KAZ"),
    KE(404, "Kenya", "KE", "KEN"),
    KI(296, "Kiribati", "KI", "KIR"),
    KP(408, "Korea, Democratic People'S Republic Of", "KP", "PRK"),
    KR(410, "Korea, Republic Of", "KR", "KOR"),
    KW(414, "Kuwait", "KW", "KWT"),
    KG(417, "Kyrgyzstan", "KG", "KGZ"),
    LA(418, "Lao People'S Democratic Republic", "LA", "LAO"),
    LV(428, "Latvia", "LV", "LVA"),
    LB(422, "Lebanon", "LB", "LBN"),
    LS(426, "Lesotho", "LS", "LSO"),
    LR(430, "Liberia", "LR", "LBR"),
    LY(434, "Libyan Arab Jamahiriya", "LY", "LBY"),
    LI(438, "Liechtenstein", "LI", "LIE"),
    LT(440, "Lithuania", "LT", "LTU"),
    LU(442, "Luxembourg", "LU", "LUX"),
    MO(446, "Macau", "MO", "MAC"),
    MK(807, "Macedonia, The Former Yugoslav Republic Of", "MK", "MKD"),
    MG(450, "Madagascar", "MG", "MDG"),
    MW(454, "Malawi", "MW", "MWI"),
    MY(458, "Malaysia", "MY", "MYS"),
    MV(462, "Maldives", "MV", "MDV"),
    ML(466, "Mali", "ML", "MLI"),
    MT(470, "Malta", "MT", "MLT"),
    MH(584, "Marshall Islands", "MH", "MHL"),
    MQ(474, "Martinique", "MQ", "MTQ"),
    MR(478, "Mauritania", "MR", "MRT"),
    MU(480, "Mauritius", "MU", "MUS"),
    YT(175, "Mayotte", "YT", "MYT"),
    MX(484, "Mexico", "MX", "MEX"),
    FM(583, "Micronesia, Federated States Of", "FM", "FSM"),
    MD(498, "Moldova, Republic Of", "MD", "MDA"),
    MC(492, "Monaco", "MC", "MCO"),
    MN(496, "Mongolia", "MN", "MNG"),
    MS(500, "Montserrat", "MS", "MSR"),
    MA(504, "Morocco", "MA", "MAR"),
    MZ(508, "Mozambique", "MZ", "MOZ"),
    MM(104, "Myanmar", "MM", "MMR"),
    NA(516, "Namibia", "NA", "NAM"),
    NR(520, "Nauru", "NR", "NRU"),
    NP(524, "Nepal", "NP", "NPL"),
    NL(528, "Netherlands", "NL", "NLD"),
    AN(530, "Netherlands Antilles", "AN", "ANT"),
    NC(540, "New Caledonia", "NC", "NCL"),
    NZ(554, "New Zealand", "NZ", "NZL"),
    NI(558, "Nicaragua", "NI", "NIC"),
    NE(562, "Niger", "NE", "NER"),
    NG(566, "Nigeria", "NG", "NGA"),
    NU(570, "Niue", "NU", "NIU"),
    NF(574, "Norfolk Island", "NF", "NFK"),
    MP(580, "Northern Mariana Islands", "MP", "MNP"),
    NO(578, "Norway", "NO", "NOR"),
    OM(512, "Oman", "OM", "OMN"),
    PK(586, "Pakistan", "PK", "PAK"),
    PW(585, "Palau", "PW", "PLW"),
    PA(591, "Panama", "PA", "PAN"),
    PG(598, "Papua New Guinea", "PG", "PNG"),
    PY(600, "Paraguay", "PY", "PRY"),
    PE(604, "Peru", "PE", "PER"),
    PH(608, "Philippines", "PH", "PHL"),
    PN(612, "Pitcairn", "PN", "PCN"),
    PL(616, "Poland", "PL", "POL"),
    PT(620, "Portugal", "PT", "PRT"),
    PR(630, "Puerto Rico", "PR", "PRI"),
    QA(634, "Qatar", "QA", "QAT"),
    RE(638, "Reunion", "RE", "REU"),
    RO(642, "Romania", "RO", "ROU"),
    RU(643, "Russian Federation", "RU", "RUS"),
    RW(646, "Rwanda", "RW", "RWA"),
    SH(654, "Saint Helena", "SH", "SHN"),
    KN(659, "Saint Kitts And Nevis", "KN", "KNA"),
    LC(662, "Saint Lucia", "LC", "LCA"),
    PM(666, "Saint Pierre And Miquelon", "PM", "SPM"),
    VC(670, "Saint Vincent And The Grenadines", "VC", "VCT"),
    WS(882, "Samoa", "WS", "WSM"),
    SM(674, "San Marino", "SM", "SMR"),
    ST(678, "Sao Tome And Principe", "ST", "STP"),
    SA(682, "Saudi Arabia", "SA", "SAU"),
    SN(686, "Senegal", "SN", "SEN"),
    CS(891, "Serbia And Montenegro", "CS", "SCG"),
    SC(690, "Seychelles", "SC", "SYC"),
    SL(694, "Sierra Leone", "SL", "SLE"),
    SG(702, "Singapore", "SG", "SGP"),
    SK(703, "Slovakia", "SK", "SVK"),
    SI(705, "Slovenia", "SI", "SVN"),
    SB(90, "Solomon Islands", "SB", "SLB"),
    SO(706, "Somalia", "SO", "SOM"),
    ZA(710, "South Africa", "ZA", "ZAF"),
    GS(239, "South Georgia And The South Sandwich Islands", "GS", "SGS"),
    ES(724, "Spain", "ES", "ESP"),
    LK(144, "Sri Lanka", "LK", "LKA"),
    SD(736, "Sudan", "SD", "SDN"),
    SR(740, "Suriname", "SR", "SUR"),
    SJ(744, "Svalbard And Jan Mayen Islands", "SJ", "SJM"),
    SZ(748, "Swaziland", "SZ", "SWZ"),
    SE(752, "Sweden", "SE", "SWE"),
    CH(756, "Switzerland", "CH", "CHE"),
    SY(760, "Syrian Arab Republic", "SY", "SYR"),
    TW(158, "Taiwan", "TW", "TWN"),
    TJ(762, "Tajikistan", "TJ", "TJK"),
    TZ(834, "Tanzania, United Republic Of", "TZ", "TZA"),
    TH(764, "Thailand", "TH", "THA"),
    TL(626, "Timor-Leste", "TL", "TLS"),
    TG(768, "Togo", "TG", "TGO"),
    TK(772, "Tokelau", "TK", "TKL"),
    TO(776, "Tonga", "TO", "TON"),
    TT(780, "Trinidad And Tobago", "TT", "TTO"),
    TN(788, "Tunisia", "TN", "TUN"),
    TR(792, "Turkey", "TR", "TUR"),
    TM(795, "Turkmenistan", "TM", "TKM"),
    TC(796, "Turks And Caicos Islands", "TC", "TCA"),
    TV(798, "Tuvalu", "TV", "TUV"),
    UA(804, "Ukraine", "UA", "UKR"),
    AE(784, "United Arab Emirates", "AE", "ARE"),
    GB(826, "United Kingdom", "GB", "GBR"),
    US(840, "United States", "US", "USA"),
    UM(581, "United States Minor Outlying Islands", "UM", "UMI"),
    UY(858, "Uruguay", "UY", "URY"),
    UZ(860, "Uzbekistan", "UZ", "UZB"),
    VU(548, "Vanuatu", "VU", "VUT"),
    VA(336, "Vatican City State (Holy See)", "VA", "VAT"),
    VE(862, "Venezuela", "VE", "VEN"),
    VN(704, "Viet Nam", "VN", "VNM"),
    VG(92, "Virgin Islands (British)", "VG", "VGB"),
    VI(850, "Virgin Islands (U.S.)", "VI", "VIR"),
    WF(876, "Wallis And Futuna Islands", "WF", "WLF"),
    EH(732, "Western Sahara", "EH", "ESH"),
    YE(887, "Yemen", "YE", "YEM"),
    ZM(894, "Zambia", "ZM", "ZMB"),
    ZW(716, "Zimbabwe", "ZW", "ZWE"),
    ;

    companion object {
        fun fromNumericCode(code: Int): CountryCodeDescription? =
            entries.find { it.numericCode == code }

        fun fromAlpha2Code(code: String): CountryCodeDescription? =
            entries.find { it.alpha2Code.equals(code, ignoreCase = true) }

        fun fromAlpha3Code(code: String): CountryCodeDescription? =
            entries.find { it.alpha3Code.equals(code, ignoreCase = true) }
    }
}
