package io.github.rafaelrabeloit.iso

/**
 * ISO 639-2
 */
enum class LanguageCodeDescription(val code: String, val description: String) {
    AAR("aa", "Afar"),
    ABK("ab", "Abkhazian"),
    AFR("af", "Afrikaans"),
    AKA("ak", "Akan"),
    AMH("am", "Amharic"),
    ARA("ar", "Arabic"),
    ARG("an", "Aragonese"),
    ASM("as", "Assamese"),
    AVA("av", "Avaric"),
    AVE("ae", "Avestan"),
    AYM("ay", "Aymara"),
    AZE("az", "Azerbaijani"),
    BAK("ba", "Bashkir"),
    BAM("bm", "Bambara"),
    BEL("be", "Belarusian"),
    BEN("bn", "Bengali"),
    BIS("bi", "Bislama"),
    BOD("bo", "Tibetan"),
    BOS("bs", "Bosnian"),
    BRE("br", "Breton"),
    BUL("bg", "Bulgarian"),
    CAT("ca", "Catalan"),
    CES("cs", "Czech"),
    CHA("ch", "Chamorro"),
    CHE("ce", "Chechen"),
    CHU("cu", "Church Slavic"),
    CHV("cv", "Chuvash"),
    COR("kw", "Cornish"),
    COS("co", "Corsican"),
    CRE("cr", "Cree"),
    CYM("cy", "Welsh"),
    DAN("da", "Danish"),
    DEU("de", "German"),
    DIV("dv", "Dhivehi"),
    DZO("dz", "Dzongkha"),
    ELL("el", "Modern Greek (1453-)"),
    ENG("en", "English"),
    EPO("eo", "Esperanto"),
    EST("et", "Estonian"),
    EUS("eu", "Basque"),
    EWE("ee", "Ewe"),
    FAO("fo", "Faroese"),
    FAS("fa", "Persian"),
    FIJ("fj", "Fijian"),
    FIN("fi", "Finnish"),
    FRA("fr", "French"),
    FRY("fy", "Western Frisian"),
    FUL("ff", "Fulah"),
    GLA("gd", "Scottish Gaelic"),
    GLE("ga", "Irish"),
    GLG("gl", "Galician"),
    GLV("gv", "Manx"),
    GRN("gn", "Guarani"),
    GUJ("gu", "Gujarati"),
    HAT("ht", "Haitian"),
    HAU("ha", "Hausa"),
    HBS("sh", "Serbo-Croatian"),
    HEB("he", "Hebrew"),
    HER("hz", "Herero"),
    HIN("hi", "Hindi"),
    HMO("ho", "Hiri Motu"),
    HRV("hr", "Croatian"),
    HUN("hu", "Hungarian"),
    HYE("hy", "Armenian"),
    IBO("ig", "Igbo"),
    IDO("io", "Ido"),
    III("ii", "Sichuan Yi"),
    IKU("iu", "Inuktitut"),
    ILE("ie", "Interlingue"),
    INA("ia", "Interlingua (International Auxiliary Language Association)"),
    IND("id", "Indonesian"),
    IPK("ik", "Inupiaq"),
    ISL("is", "Icelandic"),
    ITA("it", "Italian"),
    JAV("jv", "Javanese"),
    JPN("ja", "Japanese"),
    KAL("kl", "Kalaallisut"),
    KAN("kn", "Kannada"),
    KAS("ks", "Kashmiri"),
    KAT("ka", "Georgian"),
    KAU("kr", "Kanuri"),
    KAZ("kk", "Kazakh"),
    KHM("km", "Central Khmer"),
    KIK("ki", "Kikuyu"),
    KIN("rw", "Kinyarwanda"),
    KIR("ky", "Kirghiz"),
    KOM("kv", "Komi"),
    KON("kg", "Kongo"),
    KOR("ko", "Korean"),
    KUA("kj", "Kuanyama"),
    KUR("ku", "Kurdish"),
    LAO("lo", "Lao"),
    LAT("la", "Latin"),
    LAV("lv", "Latvian"),
    LIM("li", "Limburgan"),
    LIN("ln", "Lingala"),
    LIT("lt", "Lithuanian"),
    LTZ("lb", "Luxembourgish"),
    LUB("lu", "Luba-Katanga"),
    LUG("lg", "Ganda"),
    MAH("mh", "Marshallese"),
    MAL("ml", "Malayalam"),
    MAR("mr", "Marathi"),
    MKD("mk", "Macedonian"),
    MLG("mg", "Malagasy"),
    MLT("mt", "Maltese"),
    MON("mn", "Mongolian"),
    MRI("mi", "Maori"),
    MSA("ms", "Malay (macrolanguage)"),
    MYA("my", "Burmese"),
    NAU("na", "Nauru"),
    NAV("nv", "Navajo"),
    NBL("nr", "South Ndebele"),
    NDE("nd", "North Ndebele"),
    NDO("ng", "Ndonga"),
    NEP("ne", "Nepali (macrolanguage)"),
    NLD("nl", "Dutch"),
    NNO("nn", "Norwegian Nynorsk"),
    NOB("nb", "Norwegian Bokmål"),
    NOR("no", "Norwegian"),
    NYA("ny", "Nyanja"),
    OCI("oc", "Occitan (post 1500)"),
    OJI("oj", "Ojibwa"),
    ORI("or", "Oriya (macrolanguage)"),
    ORM("om", "Oromo"),
    OSS("os", "Ossetian"),
    PAN("pa", "Panjabi"),
    PLI("pi", "Pali"),
    POL("pl", "Polish"),
    POR("pt", "Portuguese"),
    PUS("ps", "Pushto"),
    QUE("qu", "Quechua"),
    ROH("rm", "Romansh"),
    RON("ro", "Romanian"),
    RUN("rn", "Rundi"),
    RUS("ru", "Russian"),
    SAG("sg", "Sango"),
    SAN("sa", "Sanskrit"),
    SIN("si", "Sinhala"),
    SLK("sk", "Slovak"),
    SLV("sl", "Slovenian"),
    SME("se", "Northern Sami"),
    SMO("sm", "Samoan"),
    SNA("sn", "Shona"),
    SND("sd", "Sindhi"),
    SOM("so", "Somali"),
    SOT("st", "Southern Sotho"),
    SPA("es", "Spanish"),
    SQI("sq", "Albanian"),
    SRD("sc", "Sardinian"),
    SRP("sr", "Serbian"),
    SSW("ss", "Swati"),
    SUN("su", "Sundanese"),
    SWA("sw", "Swahili (macrolanguage)"),
    SWE("sv", "Swedish"),
    TAH("ty", "Tahitian"),
    TAM("ta", "Tamil"),
    TAT("tt", "Tatar"),
    TEL("te", "Telugu"),
    TGK("tg", "Tajik"),
    TGL("tl", "Tagalog"),
    THA("th", "Thai"),
    TIR("ti", "Tigrinya"),
    TON("to", "Tonga (Tonga Islands)"),
    TSN("tn", "Tswana"),
    TSO("ts", "Tsonga"),
    TUK("tk", "Turkmen"),
    TUR("tr", "Turkish"),
    TWI("tw", "Twi"),
    UIG("ug", "Uighur"),
    UKR("uk", "Ukrainian"),
    URD("ur", "Urdu"),
    UZB("uz", "Uzbek"),
    VEN("ve", "Venda"),
    VIE("vi", "Vietnamese"),
    VOL("vo", "Volapük"),
    WLN("wa", "Walloon"),
    WOL("wo", "Wolof"),
    XHO("xh", "Xhosa"),
    YID("yi", "Yiddish"),
    YOR("yo", "Yoruba"),
    ZHA("za", "Zhuang"),
    ZHO("zh", "Chinese"),
    ZUL("zu", "Zulu"),
    ;

    companion object {
        fun fromCode(code: String): LanguageCodeDescription? =
            entries.find { it.code.equals(code, ignoreCase = true) }
    }
}
